Initial impl
AlaskaAirlines/auro-flightline pull request #2
Opened 2021-02-02 03:06 UTC by gusnaughton

# Alaska Airlines Pull Request

Adds auro-flight-line. Will update description later.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-02-03 01:57 UTC, gusnaughton commented
awaiting design approval from @erikalanghauser

2021-02-03 22:23 UTC, gusnaughton commented
@erikalanghauser's requirement for merge is to even out the dots on the flightline.

Current:
![image](https://user-images.githubusercontent.com/7005799/106817092-3bedd000-662b-11eb-8a06-987b7110a920.png)

Figma:
![image](https://user-images.githubusercontent.com/7005799/106817123-44dea180-662b-11eb-8ef5-9b7d7ecbb6b1.png)

I tried setting a margin on .slot-container and extend the ::before's width to 200% to try to get the lines to even out, but this does not equally apply depending on how many elements are in the slot. I'd love to get some advice on this one @blackfalcon 

![image](https://user-images.githubusercontent.com/7005799/106817200-62ac0680-662b-11eb-884e-e2440e8ae4c4.png)

2021-02-04 00:36 UTC, erikalanghauser approved these changes
Design approval granted! ✅

2021-02-04 03:13 UTC, blackfalcon requested changes
Great work, just need to clean up some things.

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flight-segment.scss
> +        padding-bottom: 22px;
Can this be 

var(--auro-size-lg) | 1.5rem? 24px? That's an Auro spec.

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flight-segment.scss
> +    margin-top:14px;
```suggestion
    margin-top: var(--auro-size-sm);
```

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flight-segment.scss
> +    padding-bottom: 6px;
```suggestion
    padding-bottom: var(--auro-size-xs);
```

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flightline.scss
> +    top:10px;
```suggestion
    top: 10px;
```

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flightline.scss
> +// forces each segment to take up as much space in its row to extend the ::before
2 space tabbing, please

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flightline.scss
> +        display:block;
```suggestion
        display: block;
```

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flightline.scss
> +        display:none;
```suggestion
        display: none;
```

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flightline.scss
> +    display:flex;
```suggestion
    display: flex;
```

2021-02-04 03:13 UTC, blackfalcon commented on src/style-flightline.scss
> +    justify-content:space-around;
```suggestion
    justify-content: space-around;
```

2021-02-04 03:25 UTC, blackfalcon commented
The Rollup config needs to be updated to address the multiple components within the repo. See https://github.com/AlaskaAirlines/auro-icon/blob/master/rollup.config.js for examples. 

Also, be sure to update the README for CDN install instructions.

2021-02-04 17:29 UTC, gusnaughton commented on src/auro-flightline.js
> +filter((node) => node.nodeName === 'AURO-FLIGHT-SEGMENT');
This happened due to the eslint --fix operation. Fixed, but keep an eye out for this in the future.

2021-02-04 17:39 UTC, gusnaughton commented on docs/api.md
> +| `iata`     | `iata`     | `String`  | text to display, typically a station code (SEA, PVD, AVP) |
This is not accurate - this should be text to display. We use this field to display "2/3/4/5 stops" in responsive mode.

2021-02-04 18:13 UTC, blackfalcon commented on docs/api.md
> +| `iata`     | `iata`     | `String`  | text to display, typically a station code (SEA, PVD, AVP) |
The point I am making is to be clear to the consumer. Yes, we use this to display content, but that's in the logic of the element itself. 

Is there ever a case where a consumer of the element would put in any other string other than an IATA code?

2021-02-04 18:22 UTC, blackfalcon commented on src/auro-flightline.js
> +      el.style = 'color: transparent; font-size: 0px;';
```suggestion
      el.style = 'color: transparent; font-size: 0;';
```

2021-02-05 04:23 UTC, blackfalcon requested changes
Looks great. Please address the final content updates and we are home free.

2021-02-05 04:23 UTC, blackfalcon commented on demo/demo.md
> +Guests with physical disabilities appreciate indication of whether a flight will require them to deplane, and typically optimize for the most direct route. For this reason, [Change of Gauge flights](
Delete this. While I appreciate what you are doing here, it is not the purpose of this document to sell a user on the idea. 

Again, if this is something that you feel needs to be expressed, I am all for creating a supporting document that we can link to.

2021-02-05 04:23 UTC, blackfalcon commented on src/style-flightline.scss
> +  background-color: #054687;
```suggestion
  background-color: var(--auro-color-brand-atlas-500);
```

2021-02-05 04:23 UTC, blackfalcon commented on demo/demo.md
> +<h2>Nonstop (SEAEWR)</h2>
```suggestion
## Nonstop

The following illustrates a nonstop flight, for example, SEA to EWR.
```

2021-02-05 04:23 UTC, blackfalcon commented on demo/demo.md
> +<h2>1 Connection (SEAAVP)</h2>
```suggestion
## Flight with a single connection

The following illustrates flight with one connection, for example, SEA to AVP.
```

2021-02-05 04:23 UTC, blackfalcon commented on demo/demo.md
> +<h2>1 Stopover (ANCADK)</h2>
```suggestion
## Flight with a single stopover

The following illustrates a flight with one stopover, for example, SEA to ADK.
```

2021-02-05 04:23 UTC, blackfalcon commented on demo/demo.md
> +<h2>2 Stopovers (JNUANC)</h2>
Delete this example

2021-02-05 04:23 UTC, blackfalcon commented on demo/demo.md
> +<h2>Stopover + Layover (ADKSEA)</h2>
```suggestion
## Flight with a stopover and a layover

The following illustrates flight with a stopover and a layover, for example, ADK to SEA.
```

2021-02-05 04:23 UTC, blackfalcon commented on demo/demo.md
> +<h2>Stopover Layover International Flight (ADKBCN)</h2>
```suggestion
## Multi-leg flight with layovers and stopovers

The following illustrates an international flight with stopovers and layovers, for example, ADK to BCN.
```

2021-02-05 20:19 UTC, gusnaughton commented on demo/demo.md
> +   10FEB  WED   SEA/PST     EWR/EST¥3
This is Sabre output intended for use of TPOs validating their scenario in production against our intended designs. I think this is useful and each of these availability blocks are unique to the individual demo. I think they should remain coupled - thoughts?

2021-02-05 20:23 UTC, gusnaughton commented on demo/demo.md
> +Guests with physical disabilities appreciate indication of whether a flight will require them to deplane, and typically optimize for the most direct route. For this reason, [Change of Gauge flights](
This is a legal requirement that we need to comply to. Do we want to risk engineers not travelling to that supporting document and slipping out of compliance?

2021-02-05 21:17 UTC, gusnaughton commented on demo/demo.md
> +<h2>Stopover Layover International Flight (ADKBCN)</h2>
Multi-leg flights do not exist

2021-02-05 23:34 UTC, blackfalcon commented on docs/usecases.md
> +For more information about the difference between a layover and a stopover,
```suggestion
For more information, [please see this article](https://www.turkishairlines.com/en-int/any-questions/what-is-the-difference-between-a-layover-and-a-stopover/) about the differences between a layover and a stopover.
```

2021-02-05 23:34 UTC, blackfalcon commented on docs/usecases.md
> +[please see this article.](https://www.turkishairlines.com/en-int/any-questions/what-is-the-difference-between-a-layover-and-a-stopover/)
Delete line

2021-02-05 23:36 UTC, blackfalcon commented on docs/usecases.md
> +  ```
All these blobs of data should have a preceding line of text that describes what it is.

2021-02-05 23:36 UTC, blackfalcon commented on docs/usecases.md
> +  ```dion>
This is broken

2021-02-05 23:37 UTC, blackfalcon commented on docs/usecases.md
> +## Flight with a single stopover (ANCADK)
Is this common to be written like this?  `(ANCADK)`?

2021-02-05 23:40 UTC, blackfalcon commented on demo/demo.md
> +## Component use cases
Insert line break between this header and the next content line. It's a markdown thing.

2021-02-05 23:41 UTC, blackfalcon commented on demo/demo.md
> +## Nonstop
Please add suggested descriptive text here.

2021-02-05 23:41 UTC, blackfalcon commented on demo/demo.md
> +## Flight with a single layover
Please add suggested descriptive text here.

2021-02-05 23:41 UTC, blackfalcon commented on demo/demo.md
> +## Flight with a single stopover
Please add suggested descriptive text here.

2021-02-05 23:57 UTC, blackfalcon commented on demo/demo.md
> +Guests with physical disabilities appreciate indication of whether a flight will require them to deplane, and typically optimize for the most direct route. For this reason, [Change of Gauge flights](
What is the legal requirement? That is not specified here. I see `Guests with physical disabilities appreciate indication...` and then descriptive text. 

If there is a legal requirement, say that. Be specific and direct. 

Also, never use your personal email address as a way for people to ask questions. That is why we have issues and other channels of communication. While you are the dev building this element, you are not the single point of contact for any and all issues that may arise from this tool.

2021-02-06 00:01 UTC, blackfalcon commented on docs/usecases.md
> +# Business Cases
```suggestion
# Airline use specifications
```

I feel that this should be more direct. Emphasize that there are guidelines to be followed and that there are real repercussions for not adhering to them.

2021-02-06 00:25 UTC, gusnaughton commented on docs/api.md
> +| `iata`     | `iata`     | `String`  | text to display, typically a station code (SEA, PVD, AVP) |
Yes - we currently use this when we collapse down to responsive mode '2 stops'.

2021-02-06 00:32 UTC, gusnaughton commented on docs/usecases.md
> +## Flight with a single stopover (ANCADK)
Typically the parenthesis are left out, but yes - this is Sabre and ITA terminology for describing a citypair.

2021-02-08 20:51 UTC, blackfalcon approved these changes

2021-02-08 20:51 UTC, merged

2021-02-08 20:54 UTC, blackfalcon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-flightline/v/1.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-flightline/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: