feat: switch to condensed view when content overflows
AlaskaAirlines/auro-flightline pull request #23
Opened 2021-09-01 23:07 UTC by geoffrich

# Alaska Airlines Pull Request

Fixes https://github.com/AlaskaAirlines/auro-flight/issues/19

## Summary:

- Use ResizeObserver to detect changes to element size. The RO is shared between all flightline instances.
- If an element is overflowing, switch to condensed view
- Add unit test to look at computed style of segments
- Refactor: remove --layover class

TODO:
- [ ] Is this a breaking change if people rely on the full view being displayed?
- [ ] Should stop size change too?
- [ ] Test in Safari and in Disruptions site layout
- [ ] Prevent FOUC in Firefox
- [ ] Is there any risk of an infinite loop?

Test HTML:

```html
<style>
  .grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2rem;
  }

  auro-flightline {
    resize: horizontal;
  }
</style>

<div class="grid">
  <auro-flightline id="flight1">
    <auro-flight-segment stopover iata="YAK"></auro-flight-segment>
    <auro-flight-segment stopover iata="WRG"></auro-flight-segment>
    <auro-flight-segment iata="SEA" duration="0h 40m"></auro-flight-segment>
    <auro-flight-segment iata="BOS" duration="1h 40m"></auro-flight-segment>
    <auro-flight-segment iata="DUB" duration="13h 40m"></auro-flight-segment>
  </auro-flightline>
  <auro-flightline id="flight2">
    <auro-flight-segment stopover iata="YAK"></auro-flight-segment>
    <auro-flight-segment stopover iata="WRG"></auro-flight-segment>
    <auro-flight-segment iata="SEA" duration="0h 40m"></auro-flight-segment>
    <auro-flight-segment iata="BOS" duration="1h 40m"></auro-flight-segment>
    <auro-flight-segment iata="DUB" duration="13h 40m"></auro-flight-segment>
  </auro-flightline>
</div>
```

## Type of change:

Please delete options that are not relevant.

- [x] New capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-10-01 20:44 UTC, blackfalcon commented
Given this draft PR, how do you feel about working with this polyfill that is based on the emerging spec? 

https://github.com/AlaskaAirlines/auro-flight/issues/19#issuecomment-932537409

2021-11-17 17:28 UTC, geoffrich commented on src/auro-flightline.js
> +const SMALL_BREAKPOINT = 660;
Latest commit names this with camel case.

2021-11-17 17:28 UTC, geoffrich commented on src/observer.js
> +const ro = new ResizeObserver(handleResize);
Added the above snippet and this seems to work now.

2021-11-17 17:29 UTC, geoffrich commented on src/auro-flightline.js
> +      this.condensed = val < SMALL_BREAKPOINT;
I refactored the code to be mobile-first, swapping `condensed` for `expanded`. Styles are simpler now!

2021-11-17 17:31 UTC, geoffrich commented on src/auro-flight-segment.js
> +        <div class="leg layout ${classMap(legClasses)}"></div>
Reverted this change in latest commit.

2021-11-17 17:31 UTC, geoffrich commented on src/auro-flightline.js
> +      <div class="slot-container ${classMap(classes)}">
Reverted this change in latest commit.

2021-11-17 17:34 UTC, geoffrich commented on src/style-flightline.scss
> +
Do my latest changes address your concerns here? Now the styles mirror the old code, just replacing media queries with `.expanded`.

2021-11-17 17:39 UTC, geoffrich commented
@blackfalcon finally got back to this. I think I addressed all your comments -- please take another look. Going mobile-first made things a lot cleaner.

Also, I think you linked the wrong issue to this PR -- this addresses https://github.com/AlaskaAirlines/auro-flight/issues/19. The canceled flightline will be addressed separately.

2021-11-23 02:51 UTC, blackfalcon requested changes

2021-11-23 02:51 UTC, blackfalcon commented on src/style-flightline.scss
> +.multiple.expanded ::slotted(*) {
```suggestion
.multiple.switch ::slotted(*) {
```

2021-11-23 02:51 UTC, blackfalcon commented on test/auro-flightline.test.js
> +  it('shows expanded view depending on width', async () => {
```suggestion
  it('shows switched view depending on width', async () => {
```

2021-11-23 02:51 UTC, blackfalcon commented on src/auro-flightline.js
> +const defaultBreakpoint = 414;
```suggestion
const defaultContainer= 414;
```

2021-11-23 02:51 UTC, blackfalcon commented on src/observer.js
> +/** @type {Map<Node, resizeCallback>} */
Something I have been thinking about is making utilities like these Class declarations so that we can ship them in a utility package and then users can extend the features if needed within the individual setup. 

Then each project can have these installed via NPM and we can have easier control over them when updated. 

Thoughts?

2021-12-22 22:59 UTC, geoffrich commented on src/auro-flightline.js
> +      breakpoint:  { type: Number }
Is the reasoning behind making a string just so the user better understands it's a px value? I would have concerns that if we expose it that way then they might think they can do other units as well like 50rem, 50%, etc, which would be hard to validate. Having it be a number is just simpler and we can clearly explain in the API documentation that it represents a pixel value.

2021-12-22 23:03 UTC, geoffrich commented on src/auro-flightline.js
> +    this.expanded = false;
I was thinking of it as "expanded view", i.e. showing all the stops. "switch" feels just as confusing to me.

What about `showAllStops`? Since that's what the component is doing.

Naming things is hard.

2021-12-22 23:06 UTC, geoffrich commented on src/observer.js
> +/** @type {Map<Node, resizeCallback>} */
I would prefer to move these into a common package when it becomes necessary for another component to use this functionality. Otherwise it's just another package + repo to maintain if we don't have the immediate need to share this code.

2021-12-23 00:19 UTC, geoffrich commented on src/auro-flightline.js
> +    this.expanded = false;
Renamed to "showAllStops". I'm going to resolve the other comments around this name change, but leave this one open for further discussion.

2021-12-23 00:23 UTC, geoffrich commented
Refactored according to suggested name changes. See my comments above. Also updated the tests to ignore the "ResizeObserver limit exceeded" error, which only happened in the tests. Previously, I had wrapped the call in `requestAnimationFrame` to fix this, but this was inexplicable causing several tests to be skipped. I removed the `requestAnimationFrame` and told Mocha to treat the error as a warning instead.

@blackfalcon let me know what you think of the name changes (though I know you're off for the holidays soon, so no rush)

2021-12-23 21:42 UTC, blackfalcon commented
I am approving this work given the scope is directly tied to this element's use. Abstracting this into an individual utility will be discussed in the future with a different proposal of work. 

Given the current maturity of the `@content` selector and its current availability [behind a chrome flag](https://css-tricks.com/say-hello-to-css-container-queries/), it's safe to say that by the time we get to the work needed to make this a shareable utility the official spec will be in the wild.

2021-12-23 21:43 UTC, blackfalcon approved these changes

2021-12-23 21:44 UTC, merged