perf(es5): Remove legacy es5 bundling resource #44
AlaskaAirlines/auro-flightline pull request #52
Opened 2023-05-05 04:37 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #44,

## Summary:

...

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-05-09 20:07 UTC, blackfalcon reviewed
Please delete `./index.html` from the root of the project.

2023-05-09 20:12 UTC, blackfalcon requested changes

2023-05-09 20:12 UTC, blackfalcon commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
Please replace with the following 

```
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
```

2023-05-09 20:12 UTC, blackfalcon commented on .github/settings.yml
>  labels:
Missing content

```
labels:
  - name: auro-flightline
    color: 'fa23e4'
    description:
    process: Key filter for this repo
```

2023-05-09 20:13 UTC, blackfalcon requested changes

2023-05-09 20:13 UTC, blackfalcon commented on demo/index.html
> +    </script>
this is not needed in this file

2023-05-09 20:15 UTC, blackfalcon requested changes

2023-05-09 20:17 UTC, blackfalcon reviewed
This commit is not prefixed correctly. For one, I am confused as to why adding line breaks to the code is needed as a single commit? 

Also, this is an update to the docs, so the correct prefix would be `docs`, not fix.

2023-05-09 20:20 UTC, blackfalcon requested changes

2023-05-09 20:20 UTC, blackfalcon commented on .github/workflows/testPublish.yml
> +      - run: npm run build:sass:component
Please see how the testPublish document is written in the generator. 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/.github/workflows/testPublish.yml

2023-05-09 20:22 UTC, blackfalcon requested changes

2023-05-09 20:22 UTC, blackfalcon commented on package.json
> +    "sass": "^1.62.1",
Please add support for Sass override 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/package.json#L75-L79

2023-05-09 20:23 UTC, blackfalcon requested changes

2023-05-09 20:23 UTC, blackfalcon commented on package.json
> +  "name": "@alaskaairux/auro-flightline",
You were correct to add update to `@aurodesignsystem` in the 1st place. Please add this back and remember to use `BREAKING CHANGE` in the body of the commit.

2023-05-09 20:33 UTC, blackfalcon commented on package.json
> +  "name": "@alaskaairux/auro-flightline",
Looks like this was updated in a later commit... disregard.

2023-05-09 20:48 UTC, blackfalcon commented on src/auro-flightline.js
>  import "focus-visible/dist/focus-visible.min.js";
Remove this line

2023-05-10 03:44 UTC, fajar-apri-alaska commented on src/auro-flightline.js
>  import "focus-visible/dist/focus-visible.min.js";
The focus-visible one?

2023-05-10 05:20 UTC, fajar-apri-alaska commented
I have pushed some more changes, please re-review @blackfalcon.
Thanks~

2023-05-12 19:46 UTC, blackfalcon requested changes
Please see task for missing update

- https://github.com/AlaskaAirlines/auro-flightline/issues/53

2023-05-16 19:05 UTC, blackfalcon requested changes
Please also address this missing update

- https://github.com/AlaskaAirlines/auro-flightline/issues/54

2023-05-16 19:05 UTC, blackfalcon commented on package.json
> +    "dev": "concurrently --kill-others 'npm run build:watch' 'npm run serve'",
Forgot to add the `build:watch` npm script 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/package.json#L138

2023-08-02 17:04 UTC, Izook approved these changes
![Yugi Thumb](https://media.giphy.com/media/YOyi3Olf68kjbEB3g9/giphy.gif)

2023-08-02 19:22 UTC, blackfalcon approved these changes

2023-08-02 23:55 UTC, merged