Update CSS token per new design system theming capability
AlaskaAirlines/auro-flightline pull request #59
Opened 2023-11-09 05:56 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

**Fixes:** #58 

## Summary:

- Update the design tokens to reflect the new theming conventions regarding tokens from the AuroDesignTokens and JetstreamDesignTokens repo.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-11-09 06:03 UTC, fajar-apri-alaska commented
Hi @blackfalcon, I think auro-badge `WCSS` peer dependency [here](https://github.com/AlaskaAirlines/auro-badge/blob/e173042b3691ac8b297849023c0ecb5733c10ba4/package.json#L30) needs to be updated as well to 5.0.4 for this `ci` git action to pass.
Please correct me if I'm wrong.

2023-11-13 03:02 UTC, jason-capsule42 requested changes
This PR cna not be merged while the tests are failing. Please resolve the testing.

2023-11-13 05:47 UTC, fajar-apri-alaska commented
PR is currently `BLOCKED` until below PR have been accepted, merged and shipped.
- https://github.com/AlaskaAirlines/auro-badge/pull/87

2023-11-28 01:56 UTC, blackfalcon commented
The auro-badge blocking issue has been resolved. All dependencies have been updated as well as node support.

2023-11-28 01:57 UTC, blackfalcon requested changes

2023-11-28 01:57 UTC, blackfalcon commented on docs/index.html
> +      margin: var(--ds-size-400) auto var(--ds-size-800);
```suggestion
      margin: var(--ds-size-400, $ds-size-400) auto var(--ds-size-800, $ds-size-800);
```

Please resolve all missing fallback token references.

2023-11-28 03:27 UTC, fajar-apri-alaska commented on docs/index.html
> +      margin: var(--ds-size-400) auto var(--ds-size-800);
oh wait, this one is html file, SCSS variables couldn't work here, isn't it?

2023-11-29 01:43 UTC, blackfalcon commented on docs/index.html
> +      margin: var(--ds-size-400) auto var(--ds-size-800);
Oops, that's my bad. Knee-jerk response. Nevermind.

2023-12-02 02:56 UTC, blackfalcon approved these changes

2023-12-02 02:56 UTC, merged

2023-12-02 02:58 UTC, blackfalcon commented
:tada: This PR is included in version 2.0.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-flightline/v/2.0.2)
- [GitHub release](https://github.com/AlaskaAirlines/auro-flightline/releases/tag/v2.0.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: