Feature  cancelled segment UI update
AlaskaAirlines/auro-flightline pull request #8
Opened 2021-05-18 15:55 UTC by SaiKarthikaT

# Alaska Airlines Pull Request

UI updates for cancelled segment. Add state variable 'canceled' to determine the color of flight line.

Feature: The flightline will appear as a dashed red line when the segment has been cancelled.

## Summary:

Feature: The flightline will appear as a dashed red line when the segment has been cancelled.

## Type of change:

- [ ] New capability

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-05-18 15:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/auro-flightline?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/auro-flightline?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/auro-flightline?pullRequest=8) it.</sub>

2021-05-18 17:04 UTC, geoffrich commented
@SaiKarthikaT please reference the associated GitHub issue in the PR description.

Also squash all your commits into a single `feat: add canceled status` commit and sign the CLA (see CLA Assistant comment above). Ping me if you have any issues doing this.

2021-05-18 22:59 UTC, gusnaughton commented on demo/demo.md
> +  <auro-flightline status="canceled"></auro-flightline>
This API doesn't match the one in your test

2021-05-18 23:04 UTC, gusnaughton commented
What does a cancelled flight with multiple stopovers on it look like?
AS 65: SEA KTN PSG and then say PSG WRG is cancelled - but the first 2 segments are not cancelled.

2021-05-19 12:26 UTC, blackfalcon requested changes

2021-05-19 12:26 UTC, blackfalcon commented on demo/demo.md
> +  <auro-flightline status="canceled"></auro-flightline>
```suggestion
  <auro-flightline canceled></auro-flightline>
```

2021-05-19 12:26 UTC, blackfalcon commented on src/auro-flightline.js
> +        canceled:   { type: Boolean }
```suggestion
        canceled:   { 
          type: Boolean,
          reflect: true
         }
```

https://lit-element.polymer-project.org/guide/properties#reflected-attributes

It is most likely that this will be programmatically changed.

2021-05-19 12:26 UTC, blackfalcon commented on src/auro-flightline.js
> +      'nonstop': !this.children.length && !this.canceled,
The line here is the very argument for making these enumerable attributes versus boolean. Nothing to do here @SaiKarthikaT, but just a nod to @geoffrich.

2021-05-19 12:26 UTC, blackfalcon commented on src/style-flightline.scss
> +.canceled::before{
There are a lot of shared declarations in this selector and the one preceding it. Would prefer to see something like the following to be more declarative as to what is shared and what is exclusive. 

```scss
.canceled,
.nonstop {
  &::before {
    content: "";
    height: var(--auro-size-xxxs);
    width: 100%;
    position: relative;
    top: 10px;
    z-index: 1;
  }
}

.canceled::before {
  border: 2px dashed var(--auro-color-alert-error-on-light);
}

.nonstop::before {
  display: block;
  background-color: var(--auro-color-brand-atlas-500);
}
```

2021-05-19 12:26 UTC, blackfalcon commented on test/auro-flightline.test.js
> +      <auro-flightline canceled="true">
In HTML a boolean value is a value that equals the conical string of itself. E.g. `canceled="canceled"` is true. While your code will resolve as `true` because `canceled=" "` will also equal true, the reverse `canceled="false"` will not not resolve as `false`, but `true. 

```suggestion
      <auro-flightline canceled>
```

2021-05-19 13:32 UTC, SaiKarthikaT commented
> What does a cancelled flight with multiple stopovers on it look like?
> AS 65: SEA KTN PSG and then say PSG WRG is cancelled - but the first 2 segments are not cancelled.

I don't know if stop overs or layovers matter in case of canceled trip. Let me check with UI team on their preference.

2021-05-23 18:27 UTC, blackfalcon commented
@SaiKarthikaT do you have any questions about this feedback? @geoffrich can you please assist if there are any issues?

2021-05-24 13:03 UTC, SaiKarthikaT commented
> @SaiKarthikaT do you have any questions about this feedback? @geoffrich can you please assist if there are any issues?

I'm waiting on some UI team feedback for cancellation with stop overs. Will let you know once I hear back from them.

2021-05-28 18:17 UTC, geoffrich commented on src/auro-flightline.js
> +        canceled:   { type: Boolean }
@blackfalcon I don't think this is necessary since we're not using the attribute as a styling hook, i.e. `:host([canceled])`. Or is there another reason you want the property reflected?

2021-05-28 19:02 UTC, SaiKarthikaT commented
We got feedback from Erica Breed about the canceled fligth line component. We won't be showing stop overs or lay overs in case of canceled itinerary as entire trip is impacted by cancellation.

Updated the styling on canceled line as per UI design. Ready for review now.

2021-06-02 19:47 UTC, blackfalcon commented on src/auro-flightline.js
> +        canceled:   { type: Boolean }
My reasoning was that if this were to be updated programmatically... and it's become somewhat of a reflex.

2021-06-02 19:57 UTC, blackfalcon approved these changes

2021-06-02 21:00 UTC, blackfalcon requested changes
The use of the SVG is restricted to only a non-stop flightline. When applied to a flightline with segments, it breaks the UI.

2021-06-07 19:57 UTC, blackfalcon requested changes

2021-06-07 19:57 UTC, blackfalcon commented on src/auro-flightline.js
> +        ${!this.canceled ? html` <slot></slot>`: html`<span></span>`}
```suggestion
        ${!this.canceled ? html` <slot></slot>`: html``}
```

I am not seeing any need for these spans? If that is true, let's delete these and then this PR is perfect!

2021-06-11 22:15 UTC, blackfalcon commented on src/auro-flightline.js
> +        ${!this.canceled ? html` <slot></slot>`: html`<span></span>`}
Waiting on this last update and this can be merged.

2021-06-14 17:29 UTC, blackfalcon approved these changes

2021-06-14 17:32 UTC, merged

2021-06-15 15:43 UTC, blackfalcon commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-flightline/v/1.1.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-flightline/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-06-19 22:29 UTC, gusnaughton commented
> What is the value of using the SVG over CSS for this?
> 
> I understand that if a segment is canceled, that the whole flight is canceled, but I still feel like there is value in showing the segments. Using the SVG doesn't easily allow for that. Just using CSS I was able to do this.
> 
> ![Screen Shot 2021-06-02 at 2 44 54 PM](https://user-images.githubusercontent.com/181089/120556305-29a15a00-c3b1-11eb-9da7-a5f9188d7f81.png)

This is a use case we need to account for.

AS65
SEA KTN WRG PSG JNU ANC

It's a common cancellation case for only the later half of these flights to be cancelled, and this can happen in advance. AS65 would still operate, say, to PSG, but not be able to continue that day to JNU or ANC. Was this scenario accounted for in the implementing design?